name: CreeperHeal2
main: net.pdevita.creeperheal2.CreeperHeal2
version: 2.1.1
api-version: 1.13
author: pmdevita
softdepend:
  - Movecraft
  - Factions
  - Towny

commands:
  creeperheal:
    description: CreeperHeal2 commands
    usage: /creeperheal <command>