name: Publish package to GitHub Packages
on:
  push:
  workflow_dispatch:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: |
          echo "-ssettings.gh.xml" > .mvn/maven.config
          sed -i 's/<build>/<build><finalName>creeperheal2<\/finalName>/' pom.xml
          cat pom.xml
      - name: Publish package
        run: mvn --batch-mode deploy -Djar.finalName=myCustomName
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
