name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # if you have a protection rule on your repository, you'll need to give write permission to the workflow.
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - run: |
          mvn dokka:dokka
          mvn dokka:javadoc
          cd target
          mv dokkaJavadoc javadoc
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
