name: CI

on: [workflow_dispatch, push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    - name: Extract Git short hash
      id: githash
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Extract Maven project version
      id: maven-project
      shell: bash
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
    - name: maven-settings
      uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: '[{"id": "github", "username": "dummy", "password": "${GITHUB_TOKEN_REF}"}]'
        githubServer: false
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        GITHUB_TOKEN_REF: ${{ secrets.GITHUB_TOKEN }}
    - name: Stage jar
      run: mkdir staging && cp target/CreeperHeal2*.jar staging && mv staging/CreeperHeal2*.jar staging/CreeperHeal2-dev-${{ steps.githash.outputs.sha_short }}.jar
    - name: check staging
      run: ls -la staging
    - name: Upload jar
      uses: actions/upload-artifact@v3
      with:
        name: CreeperHeal2-dev-${{ steps.githash.outputs.sha_short }}
        path: staging/CreeperHeal2-*.jar
